import React, { useState, useEffect } from 'react';
import { useRouter } from '../context/RouterContext';
import { properties } from '../data/properties';
import { areas } from '../data/areas';
import { PropertyGallery } from '../components/residences/PropertyGallery';
import { AmenityList } from '../components/residences/AmenityList';
import { ViewingForm } from '../components/forms/ViewingForm';
import { PropertyCard } from '../components/residences/PropertyCard';
import { MobileStickyActions } from '../components/common/MobileStickyActions';
import { formatTHB, getWhatsAppLink, getLineLink, siteConfig } from '../config/site';
import { NotFoundPage } from './NotFoundPage';
import { MapPin, BedDouble, Bath, Maximize, Share2, Bookmark, BookmarkCheck, MessageCircle, Train, Car, Plane, FileText, ArrowLeft, Calendar } from 'lucide-react';

interface PropertyDetailPageProps { slug: string; }

export const PropertyDetailPage: React.FC<PropertyDetailPageProps> = ({ slug }) => {
  const { navigate } = useRouter();
  const [isSaved, setIsSaved] = useState(false);
  const [shareNotice, setShareNotice] = useState(false);
  const [viewingModalOpen, setViewingModalOpen] = useState(false);
  const property = properties.find(p => p.slug === slug);

  useEffect(() => {
    window.scrollTo(0, 0);
    if (property) {
      document.title = `${property.name} | ${property.neighbourhood} | ${siteConfig.name}`;
    }
  }, [slug, property]);

  if (!property) {
    return (
      <NotFoundPage
        title="Residence Not Found"
        message="The residence you are looking for does not exist, has been leased, or has been removed from our current portfolio."
      />
    );
  }
  const areaInfo = areas.find(a => a.name.toLowerCase() === property.neighbourhood.toLowerCase());
  const similarProperties = properties.filter(p => p.id !== property.id && p.neighbourhood === property.neighbourhood).slice(0, 3);
  const handleShare = () => { navigator.clipboard?.writeText(window.location.href); setShareNotice(true); window.setTimeout(() => setShareNotice(false), 2500); };
  const whatsappUrl = getWhatsAppLink(property.name, property.id);
  const lineUrl = getLineLink();

  return <div className="pt-20 sm:pt-24 pb-28 bg-[#FBF9F5]">
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 py-4 border-b border-[#EAE5DC] flex items-center justify-between"><button onClick={()=>navigate('/residences')} className="inline-flex items-center gap-2 text-xs uppercase tracking-widest text-[#78716A] hover:text-[#18181B]"><ArrowLeft className="w-3.5 h-3.5"/>Back to All Residences</button><div className="flex items-center gap-3"><button onClick={()=>setIsSaved(!isSaved)} className="inline-flex items-center gap-1.5 px-3 py-1.5 text-xs text-[#18181B] border border-[#DDD6CB] bg-white">{isSaved?<BookmarkCheck className="w-3.5 h-3.5"/>:<Bookmark className="w-3.5 h-3.5"/>}<span className="text-[11px] uppercase tracking-wider">{isSaved?'Shortlisted':'Save to Shortlist'}</span></button><button onClick={handleShare} className="relative inline-flex items-center gap-1.5 px-3 py-1.5 text-xs text-[#18181B] border border-[#DDD6CB] bg-white"><Share2 className="w-3.5 h-3.5"/><span className="text-[11px] uppercase tracking-wider">Share</span>{shareNotice&&<span className="absolute -bottom-8 right-0 bg-[#18181B] text-white text-[10px] px-2 py-1 whitespace-nowrap">Link Copied</span>}</button></div></div>
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-6"><PropertyGallery images={property.images} propertyName={property.name}/></div>
    <div className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-10"><div className="grid grid-cols-1 lg:grid-cols-12 gap-12 items-start"><div className="lg:col-span-8 space-y-14">
      <div className="pb-8 border-b border-[#EAE5DC]"><div className="flex flex-wrap items-center gap-3 mb-2"><span className="px-3 py-1 bg-[#18181B] text-white text-[10px] uppercase font-semibold tracking-[0.2em]">DEMONSTRATION</span><span className="text-xs uppercase tracking-widest text-[#8C827A]">REF: {property.id.toUpperCase()}</span><span className="text-xs uppercase tracking-widest text-[#8C827A]">· {property.propertyType}</span></div><h1 className="font-editorial text-3xl sm:text-5xl lg:text-6xl text-[#18181B] font-normal leading-tight mb-2">{property.name}</h1><div className="flex items-center gap-2 text-sm text-[#78716A]"><MapPin className="w-4 h-4 text-[#8C827A]"/><span>{property.building}, {property.neighbourhood}</span><span>·</span><span className="text-[#18181B] font-medium">{property.bts}</span></div><div className="grid grid-cols-2 sm:grid-cols-4 gap-4 mt-8 p-5 bg-[#F2EDE4] border border-[#DDD6CB]"><Stat icon={<BedDouble className="w-4 h-4"/>} label="Bedrooms" value={String(property.bedrooms)}/><Stat icon={<Bath className="w-4 h-4"/>} label="Bathrooms" value={String(property.bathrooms)}/><Stat icon={<Maximize className="w-4 h-4"/>} label="Indicative area" value={String(property.size)}/><Stat label="Floor" value={String(property.floor)}/></div></div>
      <Section label="OVERVIEW" title="The Residence"><p className="text-sm sm:text-base text-[#4A453F] font-light leading-relaxed whitespace-pre-line">{property.description}</p></Section>
      <Section label="DEMONSTRATION DATA" title="The Building"><p className="text-sm text-[#4A453F] font-light leading-relaxed">{property.buildingDescription}</p><div className="grid grid-cols-2 sm:grid-cols-4 gap-4 p-5 bg-white border border-[#EAE5DC] text-xs"><Data label="Developer" value={property.developer || 'Not provided'}/><Data label="Completion year" value={property.yearBuilt ? String(property.yearBuilt) : 'Not provided'}/><Data label="Total floors" value={property.totalFloors ? String(property.totalFloors) : 'Not provided'}/><Data label="Total units" value={property.totalUnits ? String(property.totalUnits) : 'Not provided'}/></div><p className="text-[11px] text-[#8C827A]">Demonstration property data. Verify specifications with the owner, building management or authorised representative before publication.</p></Section>
      <Section label="RESIDENTIAL SPECIFICATIONS" title="Amenities & Facilities"><AmenityList amenities={property.amenities}/></Section>
      <Section label="ARCHITECTURAL LAYOUT" title="Floor Plan"><div className="relative aspect-[16/9] w-full bg-[#F2EDE4] border border-[#DDD6CB] flex flex-col items-center justify-center p-8 text-center"><FileText className="w-10 h-10 text-[#8C827A] mb-4"/><h4 className="font-editorial text-xl text-[#18181B] mb-2">Floor plan information</h4><p className="text-xs text-[#78716A] max-w-md mb-5">Detailed drawings, dimensions and availability should be supplied only from verified property documentation.</p><a href={whatsappUrl} className="inline-flex items-center gap-2 px-6 py-3 text-xs uppercase tracking-widest font-medium bg-[#18181B] text-[#FBF9F5]"><FileText className="w-4 h-4"/>REQUEST PROPERTY DOCUMENTS</a></div></Section>
      <Section label="NEIGHBOURHOOD CONTEXT" title={`The Location: ${property.neighbourhood}`}>{areaInfo&&<p className="text-sm text-[#4A453F] font-light leading-relaxed">{areaInfo.description}</p>}<div className="bg-white border border-[#EAE5DC] p-6"><h4 className="text-xs uppercase tracking-widest text-[#18181B] font-semibold mb-4">Nearby highlights</h4><div className="grid grid-cols-1 sm:grid-cols-2 gap-3 text-xs">{[...(property.nearby?.dining||[]),...(property.nearby?.shopping||[]),...(property.nearby?.lifestyle||[])].map((item,idx)=><div key={idx} className="flex items-center gap-2 text-[#4A453F]"><span className="w-1.5 h-1.5 rounded-full bg-[#18181B]"/><span>{item}</span></div>)}</div></div><div className="grid grid-cols-1 sm:grid-cols-3 gap-4 p-5 bg-[#F2EDE4] border border-[#DDD6CB] text-xs"><Transport icon={<Train className="w-4 h-4"/>} label="Mass Rapid Transit" value={`${property.bts} · ${property.btsDistance}`}/><Transport icon={<Car className="w-4 h-4"/>} label="Road access" value={property.transport?.expressway||'Not provided'}/><Transport icon={<Plane className="w-4 h-4"/>} label="Airport journey" value={`BKK ${property.transport?.airportBKK||'Not provided'} / DMK ${property.transport?.airportDMK||'Not provided'}`}/></div><div className="relative aspect-[21/9] w-full bg-[#E5DFD5] border border-[#DDD6CB] flex items-center justify-center text-center p-4"><MapPin className="w-5 h-5 text-[#18181B] mb-2"/><span className="text-[11px] text-[#615B54] uppercase tracking-wider">Map and exact location to be verified before publication</span></div></Section>
      <Section label="TENANCY TERMS" title="Rental Terms & Policies"><div className="grid grid-cols-1 sm:grid-cols-2 gap-4 p-6 bg-white border border-[#EAE5DC] text-xs"><Data label="Minimum lease" value={property.rentalTerms?.minimumLease||'Verify per residence'}/><Data label="Security deposit" value={property.rentalTerms?.deposit||'Verify per residence'}/><Data label="Advance rent" value={property.rentalTerms?.advanceRent||'Verify per residence'}/><Data label="Pet policy" value={property.rentalTerms?.petsPolicy||'Verify per residence'}/><Data label="Furnishing" value={property.furnished||'Verify per residence'}/><Data label="Utilities" value={property.rentalTerms?.utilities||'Verify per residence'}/></div><p className="text-[11px] text-[#8C827A]">Terms shown in demonstration data are illustrative. Confirm the actual agreement, deposits, pet rules and utility arrangements for each residence.</p></Section>
    </div><aside className="lg:col-span-4 sticky top-28 space-y-6"><div className="bg-[#FBF9F5] border border-[#E2DDD4] p-6 sm:p-8 shadow-sm"><span className="text-[10px] uppercase tracking-[0.25em] text-[#8C827A] font-semibold block mb-1">INDICATIVE MONTHLY RENT</span><div className="font-editorial text-3xl sm:text-4xl text-[#18181B] font-normal mb-1">{formatTHB(property.monthlyRent)}</div><span className="text-xs text-[#78716A] block mb-6">Demonstration pricing · verify current rent, inclusions and fees</span><div className="space-y-3 pt-4 border-t border-[#EAE5DC]"><button type="button" onClick={()=>setViewingModalOpen(true)} className="w-full inline-flex items-center justify-center gap-2 py-3.5 px-4 text-xs uppercase tracking-[0.2em] font-semibold text-[#FBF9F5] bg-[#18181B]"><Calendar className="w-4 h-4"/>OPEN VIEWING REQUEST</button>{siteConfig.contact.whatsappNumber&&<a href={whatsappUrl} className="w-full inline-flex items-center justify-center gap-2 py-3.5 px-4 text-xs uppercase tracking-[0.2em] font-semibold text-[#18181B] bg-[#EFEAE2] border border-[#DDD6CB]"><MessageCircle className="w-4 h-4"/>ENQUIRE VIA WHATSAPP</a>}{siteConfig.contact.lineUrl&&<a href={lineUrl} className="w-full inline-flex items-center justify-center gap-2 py-3 px-4 text-xs uppercase tracking-[0.2em] font-medium text-[#18181B] bg-white border border-[#DDD6CB]"><span className="font-bold text-xs">LINE</span>ENQUIRE VIA LINE</a>}</div><p className="mt-6 pt-4 border-t border-[#EAE5DC] text-[11px] text-[#78716A]">Concept prototype. Viewing availability and property details require separate confirmation.</p></div><div className="bg-[#F8F5F0] border border-[#EAE5DC] p-6"><h3 className="font-editorial text-xl text-[#18181B] mb-2 font-normal">Request Viewing Brief</h3><p className="text-xs text-[#78716A] mb-4">Prepare your preferred date and questions. No live booking channel is connected yet.</p><ViewingForm property={property}/></div></aside></div></div>
    {similarProperties.length>0&&<section className="max-w-7xl mx-auto px-4 sm:px-6 lg:px-8 mt-24 pt-16 border-t border-[#EAE5DC]"><div className="flex items-end justify-between mb-8 pb-4 border-b border-[#EAE5DC]"><div><span className="text-[10px] uppercase tracking-[0.25em] text-[#8C827A] font-semibold block mb-1">DEMONSTRATION OPTIONS</span><h2 className="font-editorial text-2xl sm:text-4xl text-[#18181B] font-normal">Similar Residences</h2></div><button onClick={()=>navigate('/residences')} className="text-xs uppercase tracking-widest text-[#18181B]">Browse All</button></div><div className="grid grid-cols-1 md:grid-cols-3 gap-8">{similarProperties.map(sim=><PropertyCard key={sim.id} property={sim}/>)}</div></section>}
    <MobileStickyActions propertyName={property.name} referenceCode={property.id} onOpenEnquiry={()=>setViewingModalOpen(true)}/>
    {viewingModalOpen&&<div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-black/70"><div className="bg-[#FBF9F5] border border-[#DDD6CB] max-w-lg w-full p-6 sm:p-8 max-h-[90vh] overflow-y-auto"><div className="flex items-center justify-between pb-3 mb-4 border-b border-[#EAE5DC]"><h3 className="font-editorial text-2xl text-[#18181B]">Viewing Request</h3><button onClick={()=>setViewingModalOpen(false)} className="text-[#615B54] p-1">✕</button></div><ViewingForm property={property} onSuccess={()=>setViewingModalOpen(false)}/></div></div>}
  </div>;
};

const Section: React.FC<{label:string;title:string;children:React.ReactNode}> = ({label,title,children}) => <section className="space-y-4 pt-8 border-t border-[#EAE5DC"><span className="text-[10px] uppercase tracking-[0.25em] text-[#8C827A] font-semibold block">{label}</span><h2 className="font-editorial text-2xl sm:text-3xl text-[#18181B] font-normal">{title}</h2>{children}</section>;
const Stat: React.FC<{icon?:React.ReactNode;label:string;value:string}> = ({icon,label,value}) => <div><span className="text-[10px] uppercase tracking-wider text-[#8C827A] block">{label}</span><span className="font-editorial text-2xl text-[#18181B] block">{value}</span>{icon&&<span className="text-[#8C827A]">{icon}</span>}</div>;
const Data: React.FC<{label:string;value:string}> = ({label,value}) => <div><span className="text-[10px] uppercase tracking-wider text-[#8C827A] block">{label}</span><span className="font-semibold text-[#18181B] mt-0.5 block">{value}</span></div>;
const Transport: React.FC<{icon:React.ReactNode;label:string;value:string}> = ({icon,label,value}) => <div className="flex items-start gap-3"><span className="text-[#8C827A]">{icon}</span><div><span className="font-semibold text-[#18181B] block">{label}</span><span className="text-[#615B54]">{value}</span></div></div>;
