import React, { useState } from 'react';
import { OwnerFormData } from '../../types';
import { CheckCircle2, Shield, Send } from 'lucide-react';

export const OwnerForm: React.FC = () => {
  const [formData, setFormData] = useState<OwnerFormData>({ name:'', email:'', whatsapp:'', line:'', propertyAddress:'', building:'', propertyType:'Condominium', bedrooms:'2', size:'', expectedMonthlyRent:'', availableFrom:'', furnished:'Fully Furnished', message:'' });
  const [submitted, setSubmitted] = useState(false);
  const [submitting, setSubmitting] = useState(false);
  const update = (key: keyof OwnerFormData, value: string) => setFormData({ ...formData, [key]: value });
  const input = 'w-full bg-white border border-[#DDD6CB] px-3.5 py-2.5 text-xs text-[#18181B] focus:outline-none focus:border-[#18181B]';
  const handleSubmit = (e: React.FormEvent) => { e.preventDefault(); setSubmitting(true); window.setTimeout(() => { setSubmitting(false); setSubmitted(true); }, 250); };

  if (submitted) return <div className="bg-[#F2EDE4] border border-[#DDD6CB] p-8 sm:p-12 text-center space-y-4"><div className="w-12 h-12 rounded-full bg-[#18181B] text-[#FBF9F5] flex items-center justify-center mx-auto"><CheckCircle2 className="w-6 h-6" /></div><h3 className="font-editorial text-2xl sm:text-3xl text-[#18181B] font-normal">Your owner brief is ready</h3><p className="text-xs sm:text-sm text-[#615B54] max-w-lg mx-auto leading-relaxed">Thank you, <strong className="text-[#18181B]">{formData.name}</strong>. This concept form has prepared an owner enquiry locally in the browser. It has <strong className="text-[#18181B]">not been sent</strong> to an agency, broker or property manager.</p><p className="text-[11px] text-[#8C827A]">A live owner enquiry and assessment workflow will be connected before commercial use.</p><button onClick={() => setSubmitted(false)} className="inline-flex items-center px-6 py-2.5 text-xs uppercase tracking-widest font-medium border border-[#18181B] text-[#18181B] hover:bg-[#18181B] hover:text-white transition-colors">Prepare Another Brief</button></div>;

  return <form onSubmit={handleSubmit} className="space-y-6 bg-[#FBF9F5] border border-[#E2DDD4] p-6 sm:p-10 shadow-sm">
    <div className="border-b border-[#EAE5DC] pb-4 mb-2"><span className="text-[10px] uppercase tracking-[0.25em] text-[#8C827A] block mb-1">Owner Enquiry · Concept Prototype</span><h3 className="font-editorial text-2xl text-[#18181B] font-normal">Property Assessment Brief</h3></div>
    <div><h4 className="text-xs uppercase tracking-widest text-[#18181B] font-semibold mb-3">1. Owner / Representative Details</h4><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field label="Full Name *"><input required placeholder="Your name" value={formData.name} onChange={e=>update('name',e.target.value)} className={input}/></Field><Field label="Email Address *"><input required type="email" placeholder="owner@domain.com" value={formData.email} onChange={e=>update('email',e.target.value)} className={input}/></Field><Field label="WhatsApp Number"><input type="tel" placeholder="+66 / +44 / +1 ..." value={formData.whatsapp} onChange={e=>update('whatsapp',e.target.value)} className={input}/></Field><Field label="LINE ID (Optional)"><input placeholder="@lineid" value={formData.line} onChange={e=>update('line',e.target.value)} className={input}/></Field></div></div>
    <div className="pt-4 border-t border-[#EAE5DC]"><h4 className="text-xs uppercase tracking-widest text-[#18181B] font-semibold mb-3">2. Property Specifications</h4><div className="grid grid-cols-1 sm:grid-cols-2 gap-4"><Field label="Building / Development Name *"><input required placeholder="Building name" value={formData.building} onChange={e=>update('building',e.target.value)} className={input}/></Field><Field label="Property Address / Area *"><input required placeholder="Address or neighbourhood" value={formData.propertyAddress} onChange={e=>update('propertyAddress',e.target.value)} className={input}/></Field><Field label="Property Type"><select value={formData.propertyType} onChange={e=>update('propertyType',e.target.value)} className={input}><option>Condominium</option><option>Penthouse</option><option>Duplex Residence</option><option>Apartment</option><option>Private Villa</option></select></Field><Field label="Bedrooms"><select value={formData.bedrooms} onChange={e=>update('bedrooms',e.target.value)} className={input}><option>1</option><option>2</option><option>3</option><option>4+</option></select></Field><Field label="Usable Area (SQ.M) *"><input required placeholder="e.g. 185" value={formData.size} onChange={e=>update('size',e.target.value)} className={input}/></Field><Field label="Expected Monthly Rent (THB)"><input placeholder="e.g. 180000" value={formData.expectedMonthlyRent} onChange={e=>update('expectedMonthlyRent',e.target.value)} className={input}/></Field><Field label="Available From"><input placeholder="Date or timing" value={formData.availableFrom} onChange={e=>update('availableFrom',e.target.value)} className={input}/></Field><Field label="Furnishing Status"><select value={formData.furnished} onChange={e=>update('furnished',e.target.value)} className={input}><option>Fully Furnished</option><option>Designer Furnished</option><option>Unfurnished</option></select></Field></div></div>
    <div className="pt-4 border-t border-[#EAE5DC]"><label className="block text-[11px] uppercase tracking-wider text-[#78716A] mb-1 font-medium">Additional Notes or Special Features</label><textarea rows={3} placeholder="Describe features or questions about the residence..." value={formData.message} onChange={e=>update('message',e.target.value)} className="w-full bg-white border border-[#DDD6CB] p-3.5 text-xs text-[#18181B] focus:outline-none focus:border-[#18181B]"/></div>
    <div className="p-4 bg-[#F2EDE4] border border-[#E2DDD4] flex items-start gap-3 text-xs text-[#615B54]"><Shield className="w-4 h-4 text-[#8C827A] shrink-0 mt-0.5"/><p className="text-[11px] leading-relaxed">Concept prototype only. Information entered here remains in the browser and is not transmitted or stored by this demo flow. Commercial owner services, representation terms and data handling will be defined separately.</p></div>
    <button type="submit" disabled={submitting} className="w-full inline-flex items-center justify-center gap-2 py-4 px-8 text-xs uppercase tracking-[0.2em] font-medium text-[#FBF9F5] bg-[#18181B] hover:bg-[#2D2B29] transition-all border border-[#18181B]"><Send className="w-3.5 h-3.5"/><span>{submitting?'Preparing Brief...':'PREPARE OWNER BRIEF'}</span></button>
  </form>;
};

const Field: React.FC<{label:string;children:React.ReactNode}> = ({label,children}) => <div><label className="block text-[11px] uppercase tracking-wider text-[#78716A] mb-1 font-medium">{label}</label>{children}</div>;
