import React, { useState } from 'react';
import { useRouter } from '../../context/RouterContext';
import { CheckCircle2, ArrowRight, ArrowLeft, Check, MessageCircle } from 'lucide-react';
import { getWhatsAppLink } from '../../config/site';

export const PersonalSearchForm: React.FC = () => {
  const { navigate } = useRouter();
  const [step, setStep] = useState(1);
  const [submitted, setSubmitted] = useState(false);
  const [data, setData] = useState({ move:'Within 1 month', duration:'12+ months', areas:['Thonglor','Phrom Phong'], bedrooms:'2', budget:'฿150,000 – ฿250,000 / month', priorities:['City view','BTS/MRT proximity','Pool'], name:'', email:'', whatsapp:'', line:'' });
  const areas=['Thonglor','Ekkamai','Phrom Phong','Sukhumvit','Asoke','Sathorn','Silom','Ratchadamri','Langsuan','Wireless Road','Riverside','Ari'];
  const priorities=['City view','River view','Pool','Gym','Large living space','Quiet location','BTS/MRT proximity','Shopping','Restaurants','International schools','Pet friendly','Parking'];
  const budgets=['Under ฿80,000 / month','฿80,000 – ฿150,000 / month','฿150,000 – ฿250,000 / month','฿250,000 – ฿400,000 / month','฿400,000+ / month'];
  const input='w-full bg-white border border-[#DDD6CB] px-3.5 py-2.5 text-xs';
  const update=(key:string,value:string)=>setData({...data,[key]:value});
  const toggle=(key:'areas'|'priorities',value:string)=>setData({...data,[key]:data[key].includes(value)?data[key].filter(x=>x!==value):[...data[key],value]});
  if(submitted) return <div className="max-w-2xl mx-auto bg-[#FBF9F5] border border-[#E2DDD4] p-8 sm:p-14 text-center shadow-lg"><div className="w-14 h-14 bg-[#18181B] text-[#FBF9F5] rounded-full flex items-center justify-center mx-auto mb-6"><CheckCircle2 className="w-7 h-7"/></div><h3 className="font-editorial text-3xl sm:text-4xl text-[#18181B] mb-4">Your search brief is ready.</h3><p className="text-sm text-[#615B54] leading-relaxed max-w-lg mx-auto mb-8">This concept questionnaire has prepared your preferences locally in the browser. Nothing has been sent to or stored by an agency, owner or property manager.</p><div className="p-6 bg-[#F2EDE4] border border-[#DDD6CB] text-left text-xs space-y-2 mb-8"><div className="text-[10px] uppercase tracking-widest text-[#8C827A] font-semibold">Search Brief Preview</div><div><strong>Client:</strong> {data.name} ({data.email})</div><div><strong>Timeline:</strong> {data.move} · <strong>Duration:</strong> {data.duration}</div><div><strong>Areas:</strong> {data.areas.join(', ')||'Any selected area'}</div><div><strong>Bedrooms:</strong> {data.bedrooms} · <strong>Budget:</strong> {data.budget}</div></div><div className="flex flex-col sm:flex-row justify-center gap-3"><a href={getWhatsAppLink()} target="_blank" rel="noopener noreferrer" className="px-6 py-3.5 bg-[#18181B] hover:bg-[#2D2B29] text-[#FBF9F5] text-xs uppercase tracking-widest inline-flex items-center justify-center gap-2 transition-colors"><MessageCircle className="w-3.5 h-3.5 text-[#25D366]"/><span>WhatsApp Concierge</span></a><button onClick={()=>navigate('/residences')} className="px-6 py-3.5 bg-white border border-[#18181B] text-[#18181B] text-xs uppercase tracking-widest hover:bg-[#F2EDE4] transition-colors">Explore Residences</button><button onClick={()=>{setSubmitted(false);setStep(1)}} className="px-5 py-3.5 border border-[#DDD6CB] text-[#615B54] text-xs uppercase tracking-widest hover:text-[#18181B] transition-colors">Modify Brief</button></div></div>;
  const next=()=>{if(step<7){setStep(step+1);window.scrollTo({top:120,behavior:'smooth'})}};
  const prev=()=>{if(step>1){setStep(step-1);window.scrollTo({top:120,behavior:'smooth'})}};
  const options=(items:string[],key:'areas'|'priorities')=><div className="grid grid-cols-2 sm:grid-cols-3 gap-2.5">{items.map(x=><button type="button" key={x} onClick={()=>toggle(key,x)} className={`py-3 px-4 text-xs font-medium border text-left flex justify-between ${data[key].includes(x)?'bg-[#18181B] text-white border-[#18181B]':'bg-white border-[#DDD6CB]'}`}>{x}{data[key].includes(x)&&<Check className="w-3.5 h-3.5"/>}</button>)}</div>;
  const choices=(items:{v:string;s:string}[],key:'move'|'duration'|'bedrooms')=><div className="grid grid-cols-1 sm:grid-cols-2 gap-3">{items.map(x=><button type="button" key={x.v} onClick={()=>update(key,x.v)} className={`p-5 text-left border ${data[key]===x.v?'border-[#18181B] bg-[#F2EDE4]':'border-[#DDD6CB] bg-white'}`}><span className="font-editorial text-lg block">{x.v}</span><span className="text-[11px] text-[#8C827A] mt-1 block">{x.s}</span></button>)}</div>;
  return <div className="max-w-3xl mx-auto bg-[#FBF9F5] border border-[#E2DDD4] shadow-md p-6 sm:p-12"><div className="mb-10 pb-6 border-b border-[#EAE5DC] flex justify-between items-center"><div><span className="text-[10px] uppercase tracking-[0.25em] text-[#8C827A] block mb-1">Personal Search · Concept Prototype</span><h2 className="font-editorial text-2xl sm:text-3xl">Step {step} of 7</h2></div><div className="flex gap-1">{[1,2,3,4,5,6,7].map(n=><span key={n} className={`h-1.5 ${n===step?'w-8 bg-[#18181B]':'w-4 bg-[#DDD6CB]'}`}/>)}</div></div><form onSubmit={e=>{e.preventDefault();setSubmitted(true)}}>
    {step===1&&<Panel title="When do you want to move?"><p>Choose an indicative target; actual availability must be confirmed for each residence.</p>{choices([{v:'Immediately',s:'Immediate move-in target'},{v:'Within 1 month',s:'Next 30 days'},{v:'1–3 months',s:'Planning ahead'},{v:'3+ months',s:'Future relocation'}],'move')}</Panel>}
    {step===2&&<Panel title="How long will you stay?"><p>Lease length varies by residence and agreement.</p>{choices([{v:'1–3 months',s:'Shorter stay preference'},{v:'3–6 months',s:'Mid-term preference'},{v:'6–12 months',s:'Longer flexible stay'},{v:'12+ months',s:'Longer-term preference'}],'duration')}</Panel>}
    {step===3&&<Panel title="Preferred Areas"><p>Select one or more Bangkok areas for your search brief.</p>{options(areas,'areas')}</Panel>}
    {step===4&&<Panel title="Number of Bedrooms"><p>Space ranges are indicative only; actual layouts vary by residence.</p>{choices([{v:'Studio',s:'Compact'},{v:'1',s:'One bedroom'},{v:'2',s:'Two bedrooms'},{v:'3',s:'Three bedrooms'},{v:'4+',s:'Four or more'}],'bedrooms')}</Panel>}
    {step===5&&<Panel title="Monthly Budget"><p>Illustrative budget bands for the prototype; current asking rents must be verified.</p><div className="space-y-2">{budgets.map(x=><button type="button" key={x} onClick={()=>update('budget',x)} className={`w-full p-4 text-left border ${data.budget===x?'border-[#18181B] bg-[#F2EDE4]':'border-[#DDD6CB] bg-white'}`}>{x}</button>)}</div></Panel>}
    {step===6&&<Panel title="Priorities"><p>Select the features that matter most to you.</p>{options(priorities,'priorities')}</Panel>}
    {step===7&&<Panel title="Your Details"><p>These fields are used only to preview the brief in this prototype and are not transmitted.</p><div className="grid sm:grid-cols-2 gap-4"><Field label="Full Name"><input required value={data.name} onChange={e=>update('name',e.target.value)} className={input}/></Field><Field label="Email"><input required type="email" value={data.email} onChange={e=>update('email',e.target.value)} className={input}/></Field><Field label="WhatsApp"><input value={data.whatsapp} onChange={e=>update('whatsapp',e.target.value)} className={input}/></Field><Field label="LINE"><input value={data.line} onChange={e=>update('line',e.target.value)} className={input}/></Field></div></Panel>}
    <div className="mt-10 pt-6 border-t border-[#EAE5DC] flex justify-between gap-3"><button type="button" disabled={step===1} onClick={prev} className="inline-flex items-center gap-2 px-5 py-3 border border-[#DDD6CB] text-xs uppercase tracking-widest disabled:opacity-40"><ArrowLeft className="w-4 h-4"/>Back</button>{step<7?<button type="button" onClick={next} className="inline-flex items-center gap-2 px-6 py-3 bg-[#18181B] text-white text-xs uppercase tracking-widest">Continue<ArrowRight className="w-4 h-4"/></button>:<button type="submit" className="px-6 py-3 bg-[#18181B] text-white text-xs uppercase tracking-widest">Prepare Search Brief</button>}</div></form></div>;
};
const Panel:React.FC<{title:string;children:React.ReactNode}>=({title,children})=><div className="space-y-6"><h3 className="font-editorial text-2xl sm:text-3xl">{title}</h3>{children}</div>;
const Field:React.FC<{label:string;children:React.ReactNode}>=({label,children})=><div><label className="block text-[11px] uppercase tracking-wider text-[#78716A] mb-1">{label}</label>{children}</div>;
